#!/bin/bash

python3 -m pytest --verbose --numprocesses=auto --ignore=scripts/copy_from_upstream/repos

if [ $? -eq 0 ]; then
    echo "PASS: liboqs"
    exit 0
else
    echo "FAIL: liboqs"
    exit -1
fi

